image:
  - Visual Studio 2019
  - Visual Studio 2017

cache:
  - c:\users\appveyor\clcache
  - c:\local\boost_1_69_0
environment:
  BOOST_ROOT: C:\local\boost_1_69_0
  BOOST_LIB_PATH_X64: C:\local\boost_1_69_0\lib64-msvc-14.1
  BOOST_LIB_PATH_X32: C:\local\boost_1_69_0\lib32-msvc-14.1

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

install:
  - ps: Write-Host "Checking for Boost 1.69.0 x64...";$boostdir  = Test-Path $Env:BOOST_LIB_PATH_X64;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.69.0 x64...";$exePath = "$Env:TEMP\boost_1_69_0-msvc-14.1-64.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.69.0%2Fbinaries%2Fboost_1_69_0-msvc-14.1-64.exe', $exePath);Write-Host "Installing Boost 1.69.0 x64...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.69.0 x64 installed!" -ForegroundColor Green
  - ps: Write-Host "Checking for Boost 1.69.0 x32...";$boostdir  = Test-Path $Env:BOOST_LIB_PATH_X32;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.69.0 x32...";$exePath = "$Env:TEMP\boost_1_69_0-msvc-14.1-32.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.69.0%2Fbinaries%2Fboost_1_69_0-msvc-14.1-32.exe', $exePath);Write-Host "Installing Boost 1.69.0 x32...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.69.0 x32 installed!" -ForegroundColor Green

build_script:
  - ps: Write-Host "Building solution for Visual Studio 2019 x64 Platform"
  - ps: pushd
  - md build-vs19-x64
  - cd build-vs19-x64
  - cmake -G "Visual Studio 16 2019" -A x64 ..
  - MSBuild Adon.sln /p:Configuration=Release /m
  - src\Release\cryptotest.exe
  - ps: popd

  - ps: Write-Host "Building solution for Visual Studio 2019 x86 Platform"
  - ps: pushd
  - md build-vs19-x86
  - cd build-vs19-x86
  - cmake -G "Visual Studio 16 2019" -A Win32 ..
  - MSBuild Adon.sln /p:Configuration=Release /p:Platform=Win32 /m
  - src\Release\cryptotest.exe
  - ps: popd